"""Partner API key generation, hashing, and scope vocabulary.

See `docs/business/partner-api-v1-scope.md` (Auth model section) for design.

The wire format is ``vck_<key_id>.<secret>``:

* ``vck_`` — fixed prefix (VantageClaw key)
* ``<key_id>`` — URL-safe random public identifier, indexed for lookup
* ``.`` — unambiguous separator (``token_urlsafe`` never emits it)
* ``<secret>`` — URL-safe random high-entropy half, hashed at rest

Both segments are generated by ``secrets.token_urlsafe`` with sufficient
entropy that brute-force is infeasible even before PBKDF2 hardening.
"""

from __future__ import annotations

import base64
import hashlib
import hmac
import secrets

PREFIX = "vck_"

# Separator between key_id and secret. Must NOT be a character that
# ``secrets.token_urlsafe`` can emit (it outputs ``[A-Za-z0-9_-]``), so we
# use ``.`` — unambiguous to parse with ``partition``.
SEPARATOR = "."

# Entropy: 24 bytes (~32 chars url-safe base64) for key_id, 32 bytes (~43
# chars) for secret. Total token length ~83 chars including prefix and
# separators. Comfortably above any brute-force budget.
KEY_ID_BYTES = 24
SECRET_BYTES = 32

ITERATIONS = 200_000
SALT_BYTES = 16

# === Scope vocabulary =====================================================

# Real v1 scopes — granted to keys via the admin CRUD endpoint.
REAL_SCOPES: frozenset[str] = frozenset(
    {
        "webhooks:manage",
        "identity:read",
    }
)

# Reserved v1+ scopes — rejected at key creation (422). These slot in as
# real scopes when the corresponding endpoint or resource ships.
RESERVED_SCOPES: frozenset[str] = frozenset(
    {
        # First resource families (added per real partner conversation)
        "leads:read",
        "leads:write",
        "intakes:read",
        "intakes:write",
        "records:read",
        "records:write",
        # Skill authoring (deferred per project_skill_authoring_deferred.md)
        "skills:read",
        "skills:author",
        "skills:execute",
        # Future surfaces
        "agents:invoke",
        "tenants:provision",
    }
)

# Sanity: real and reserved must be disjoint.
assert REAL_SCOPES.isdisjoint(RESERVED_SCOPES), (
    "REAL_SCOPES and RESERVED_SCOPES must be disjoint"
)


class ReservedScopeError(ValueError):
    """Raised when a key creation attempts to grant a reserved-but-not-yet-real scope."""

    def __init__(self, scope: str) -> None:
        self.scope = scope
        super().__init__(
            f"Scope '{scope}' is reserved for a future API version and cannot be granted in v1"
        )


class UnknownScopeError(ValueError):
    """Raised when a key creation requests a scope outside the union of real + reserved."""

    def __init__(self, scope: str) -> None:
        self.scope = scope
        super().__init__(f"Scope '{scope}' is not a known partner API scope")


def validate_scopes(requested: list[str]) -> list[str]:
    """Validate that ``requested`` scopes are all REAL scopes.

    Returns the deduplicated, sorted scope list if every requested scope is
    in ``REAL_SCOPES``.

    Raises:
        ReservedScopeError: a requested scope is reserved (future version).
        UnknownScopeError: a requested scope is neither real nor reserved.
    """
    seen = set()
    for scope in requested:
        if scope in RESERVED_SCOPES:
            raise ReservedScopeError(scope)
        if scope not in REAL_SCOPES:
            raise UnknownScopeError(scope)
        seen.add(scope)
    return sorted(seen)


# === Token generation + hashing ===========================================


def _b64encode(value: bytes) -> str:
    return base64.urlsafe_b64encode(value).decode("utf-8").rstrip("=")


def _b64decode(value: str) -> bytes:
    padding = "=" * (-len(value) % 4)
    return base64.urlsafe_b64decode(value + padding)


def generate_partner_token() -> tuple[str, str, str]:
    """Generate a new partner API token.

    Wire format: ``vck_<key_id>.<secret>``. ``.`` is used as the separator
    because ``secrets.token_urlsafe`` outputs ``[A-Za-z0-9_-]`` — both ``_``
    and ``-`` can appear inside key_id or secret. ``.`` cannot. Using ``_``
    would make the wire format ambiguous to parse.

    Returns:
        ``(full_token, key_id, secret)`` — caller stores ``key_id`` and the
        hash of ``secret`` (via :func:`hash_partner_secret`), and returns
        ``full_token`` to the partner exactly once.
    """
    key_id = secrets.token_urlsafe(KEY_ID_BYTES)
    secret = secrets.token_urlsafe(SECRET_BYTES)
    full_token = f"{PREFIX}{key_id}{SEPARATOR}{secret}"
    return full_token, key_id, secret


def parse_partner_token(token: str) -> tuple[str, str] | None:
    """Parse the wire-format token into ``(key_id, secret)``.

    Returns ``None`` if the token is malformed (wrong prefix, missing
    separator, empty halves). The caller is responsible for treating any
    parse failure as 401 — never disclose the failure mode.
    """
    if not token.startswith(PREFIX):
        return None
    body = token[len(PREFIX) :]
    if SEPARATOR not in body:
        return None
    key_id, _, secret = body.partition(SEPARATOR)
    if not key_id or not secret:
        return None
    return key_id, secret


def hash_partner_secret(secret: str) -> str:
    """Hash the secret half of a partner token using PBKDF2-HMAC-SHA256."""
    salt = secrets.token_bytes(SALT_BYTES)
    digest = hashlib.pbkdf2_hmac("sha256", secret.encode("utf-8"), salt, ITERATIONS)
    return f"pbkdf2_sha256${ITERATIONS}${_b64encode(salt)}${_b64encode(digest)}"


def verify_partner_secret(secret: str, stored_hash: str) -> bool:
    """Verify a plaintext secret against a stored PBKDF2 hash representation."""
    try:
        algorithm, iterations, salt_b64, digest_b64 = stored_hash.split("$")
    except ValueError:
        return False
    if algorithm != "pbkdf2_sha256":
        return False
    try:
        iterations_int = int(iterations)
    except ValueError:
        return False
    salt = _b64decode(salt_b64)
    expected_digest = _b64decode(digest_b64)
    candidate = hashlib.pbkdf2_hmac(
        "sha256",
        secret.encode("utf-8"),
        salt,
        iterations_int,
    )
    return hmac.compare_digest(candidate, expected_digest)
